# Homework 1: Data Reading & Manipulation

In this homework, you will practice:
1. Reading data from CSV files and APIs
2. Data manipulation techniques covered in Week 2

# Section 1: Reading Data

In [7]:
#IMPORT PANDAS TOOLS
import pandas as pd

In [8]:
democracy_gdp_filepath = '../../data/hw/democracy_gdp.csv'
democracy_gdp = pd.read_csv(democracy_gdp_filepath)
democracy_gdp.head(4)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.65
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.65

In [9]:
democracy_gdp.tail(20)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
5580,VNM,2005,0.052,NaN,NaN,0.543,0.532,0.459,0.304,1.772
5581,VNM,2006,0.053,NaN,NaN,0.543,0.532,0.459,0.311,1.772
5582,VNM,2007,0.053,NaN,NaN,0.543,0.532,0.471,0.303,1.772
5583,VNM,2008,0.053,NaN,NaN,0.543,0.532,0.478,0.303,1.772
5584,VNM,2009,0.049,NaN,NaN,0.543,0.532,0.478,0.303,1.772
5585,VNM,2010,0.051,NaN,NaN,0.543,0.532,0.478,0.303,1.772
5586,VNM,2011,0.050,NaN,NaN,0.543,0.532,0.474,0.303,1.772
5587,VNM,2012,0.049,NaN,NaN,0.543,0.532,0.471,0.303,1.772
5588,VNM,2013,0.048,NaN,NaN,0.484,0.416,0.471,0.280,1.772
5589,VNM,2014,0.049,NaN,NaN,0.484,0.416,0.471,0.280,1.772
5590,VNM,2015,0.050,NaN,NaN,0.484,0.416,0.471,0.280,1.772
5591,VNM,2016,0.046,NaN,NaN,0.484,0.416,0.499,0.280,1.772
5592,VNM,2017,0.044,NaN,NaN,0.508,0.423,0.499,0.256,1.260
5593,VNM,2018,0.044,NaN,NaN,0.508,0.423,0.499,0.216,1.260
5594,VNM,2019,0.044,NaN,NaN,0.508,0.396,0.505,0.203,1.404
5595,VNM,2020,0.044,NaN,NaN,0.489,0.373,0.495,0.206,1.255
5596,VNM,2021,0.042,NaN,NaN,0.517,0.390,0.526,0.177,1.977
5597,VNM,2022,0.025,NaN,NaN,0.517,0.372,0.531,0.186,1.977
5598,VNM,2023,0.021,NaN,NaN,0.517,0.364,0.513,0.187,1.571
5599,VNM,2024,0.021,NaN,NaN,0.477,0.364,0.514,0.176,1.963

In [10]:
democracy_gdp.info

<bound method DataFrame.info of      country  year  v2x_frassoc_thick  NGDPDPC  NGDP_RPCH  v2x_pubcorr  \
0        AFG  1990              0.063      NaN        NaN        0.556
1        AFG  1991              0.068      NaN        NaN        0.556
2        AFG  1992              0.134      NaN        NaN        0.645
3        AFG  1993              0.159      NaN        NaN        0.843
4        AFG  1994              0.159      NaN        NaN        0.843
...      ...   ...                ...      ...        ...          ...
5595     VNM  2020              0.044      NaN        NaN        0.489
5596     VNM  2021              0.042      NaN        NaN        0.517
5597     VNM  2022              0.025      NaN        NaN        0.517
5598     VNM  2023              0.021      NaN        NaN        0.517
5599     VNM  2024              0.021      NaN        NaN        0.477

      v2xnp_regcorr  v2xel_frefair  v2x_freexp  v2elembcap
0             0.538          0.069       0.085      -1.650
1             0.538          0.069       0.074      -1.650
2             0.736          0.028       0.071      -1.650
3             0.909          0.000       0.069      -1.650
4             0.909          0.000       0.069      -1.650
...             ...            ...         ...         ...
5595          0.373          0.495       0.206       1.255
5596          0.390          0.526       0.177       1.977
5597          0.372          0.531       0.186       1.977
5598          0.364          0.513       0.187       1.571
5599          0.364          0.514       0.176       1.963

[5600 rows x 10 columns]>

### 1.1.2 Green house gas (GHG) Emissions Data

Load the `ghg.csv` file.

In [11]:
ghg_file_path = '../../data/hw/ghg.csv'
ghg = pd.read_csv(ghg_file_path)
ghg.tail(3)

            Country  year     emissions
11445  GLOBAL TOTAL  2021  51568.250032
11446  GLOBAL TOTAL  2022  51968.471601
11447  GLOBAL TOTAL  2023  52962.900859

In [12]:
ghg.head(20)

   Country  year  emissions
0    Aruba  1970   0.036713
1    Aruba  1971   0.041538
2    Aruba  1972   0.052391
3    Aruba  1973   0.057360
4    Aruba  1974   0.056630
5    Aruba  1975   0.070743
6    Aruba  1976   0.069793
7    Aruba  1977   0.080624
8    Aruba  1978   0.085484
9    Aruba  1979   0.089491
10   Aruba  1980   0.093463
11   Aruba  1981   0.096671
12   Aruba  1982   0.095760
13   Aruba  1983   0.098523
14   Aruba  1984   0.113145
15   Aruba  1985   0.118789
16   Aruba  1986   0.128518
17   Aruba  1987   0.143452
18   Aruba  1988   0.157628
19   Aruba  1989   0.212867

## 1.2 Reading Data from an API

YOU MUST RUN THE NEXT CELL TO DOWNLOAD GDP AND POPULATION DATA

In [13]:
import requests
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    df = pd.read_xml(io.BytesIO(response.content))
    return df

### 1.2.1 Download GDP Data (1990-2026)

Download GDP per capita data for a different set of countries than those in the CSV files.

In [19]:
gdp_data = download_worldbank(
    indicator='NY.GDP.PCAP.CD',
    date_start= 1990,
    date_end= 2026,
    countries= ['AUS', 'CA', 'GBR']
)
gdp_data.head(2)

gdp_data2 = download_worldbank(
    indicator='NY.GDP.PCAP.CD',
    date_start= 1990,
    date_end= 2026,
    countries= ['AUS', 'CA', 'GBR']
)
gdp_data2.head(5)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),Australia,AUS,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),Australia,AUS,2024,64603.985631,NaN,NaN,1
2,GDP per capita (current US$),Australia,AUS,2023,65058.377315,NaN,NaN,1
3,GDP per capita (current US$),Australia,AUS,2022,65169.519112,NaN,NaN,1
4,GDP per capita (current US$),Australia,AUS,2021,60758.904440,NaN,NaN,1

In [17]:
gdp_data.tail(5)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
103,GDP per capita (current US$),United Kingdom,GBR,1994,19709.238098,NaN,NaN,1
104,GDP per capita (current US$),United Kingdom,GBR,1993,18389.019568,NaN,NaN,1
105,GDP per capita (current US$),United Kingdom,GBR,1992,20487.170785,NaN,NaN,1
106,GDP per capita (current US$),United Kingdom,GBR,1991,19900.726651,NaN,NaN,1
107,GDP per capita (current US$),United Kingdom,GBR,1990,19095.466998,NaN,NaN,1

In [20]:
gdp_data

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),Australia,AUS,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),Australia,AUS,2024,64603.985631,NaN,NaN,1
2,GDP per capita (current US$),Australia,AUS,2023,65058.377315,NaN,NaN,1
3,GDP per capita (current US$),Australia,AUS,2022,65169.519112,NaN,NaN,1
4,GDP per capita (current US$),Australia,AUS,2021,60758.904440,NaN,NaN,1
...,...,...,...,...,...,...,...,...
103,GDP per capita (current US$),United Kingdom,GBR,1994,19709.238098,NaN,NaN,1
104,GDP per capita (current US$),United Kingdom,GBR,1993,18389.019568,NaN,NaN,1
105,GDP per capita (current US$),United Kingdom,GBR,1992,20487.170785,NaN,NaN,1
106,GDP per capita (current US$),United Kingdom,GBR,1991,19900.726651,NaN,NaN,1
107,GDP per capita (current US$),United Kingdom,GBR,1990,19095.466998,NaN,NaN,1

### 1.2.2 Download Population Data (1990-2026)

Download population data for the same countries.

In [24]:
population_indicator = 'SP.POP.TOTL'

country = [
    "USA",  # United States of America
    "CAN",  # Canada
    "MEX",  # Mexico
    "GBR",  # United Kingdom of Great Britain and Northern Ireland
    "FRA",  # France
    "DEU",  # Germany (Deutschland)
    "JPN",  # Japan
    "AUS"   # Australia
]

pop_data = download_worldbank(
    indicator=population_indicator,
    countries=country,
    date_start=1990,
    date_end=2026
)
pop_data.tail(3)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
285,"Population, total",United States,USA,1992,256514000.0,NaN,NaN,0
286,"Population, total",United States,USA,1991,252981000.0,NaN,NaN,0
287,"Population, total",United States,USA,1990,249623000.0,NaN,NaN,0

In [22]:
pop_data.head(10)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"Population, total",Australia,AUS,2025,NaN,NaN,NaN,0
1,"Population, total",Australia,AUS,2024,27196812.0,NaN,NaN,0
2,"Population, total",Australia,AUS,2023,26659922.0,NaN,NaN,0
3,"Population, total",Australia,AUS,2022,26018721.0,NaN,NaN,0
4,"Population, total",Australia,AUS,2021,25685412.0,NaN,NaN,0
5,"Population, total",Australia,AUS,2020,25649248.0,NaN,NaN,0
6,"Population, total",Australia,AUS,2019,25334826.0,NaN,NaN,0
7,"Population, total",Australia,AUS,2018,24963258.0,NaN,NaN,0
8,"Population, total",Australia,AUS,2017,24592588.0,NaN,NaN,0
9,"Population, total",Australia,AUS,2016,24190907.0,NaN,NaN,0

# Section 2: Data Manipulation

Now let's practice the data manipulation techniques from Week 2.

## 2.1 Select Columns

Select specific columns from the democracy_gdp dataset.

In [25]:
gdp_data['country']

0           Australia
1           Australia
2           Australia
3           Australia
4           Australia
            ...
103    United Kingdom
104    United Kingdom
105    United Kingdom
106    United Kingdom
107    United Kingdom
Name: country, Length: 108, dtype: object

In [26]:
gdp_data['date']

0      2025
1      2024
2      2023
3      2022
4      2021
       ...
103    1994
104    1993
105    1992
106    1991
107    1990
Name: date, Length: 108, dtype: int64

In [27]:
gdp_data.indicator.head(5)

0    GDP per capita (current US$)
1    GDP per capita (current US$)
2    GDP per capita (current US$)
3    GDP per capita (current US$)
4    GDP per capita (current US$)
Name: indicator, dtype: object

## 2.2 Filter Rows

Filter rows based on conditions.

In [28]:
gdp_data.date.unique()

array([2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015,
       2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004,
       2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993,
       1992, 1991, 1990])

In [29]:
gdp_data.query("date == 2022")

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
3,GDP per capita (current US$),Australia,AUS,2022,65169.519112,NaN,NaN,1
39,GDP per capita (current US$),Canada,CAN,2022,56256.800726,NaN,NaN,1
75,GDP per capita (current US$),United Kingdom,GBR,2022,47057.043229,NaN,NaN,1

## 2.3 Multiple Conditions

Filter using multiple conditions.

In [30]:
gdp_data.query("country == 'Australia' & date>2021")

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),Australia,AUS,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),Australia,AUS,2024,64603.985631,NaN,NaN,1
2,GDP per capita (current US$),Australia,AUS,2023,65058.377315,NaN,NaN,1
3,GDP per capita (current US$),Australia,AUS,2022,65169.519112,NaN,NaN,1

## 2.4 Filter in a List

Filter rows where column value is in a list.

In [31]:
gdp_data[['indicator', 'date']]

                        indicator  date
0    GDP per capita (current US$)  2025
1    GDP per capita (current US$)  2024
2    GDP per capita (current US$)  2023
3    GDP per capita (current US$)  2022
4    GDP per capita (current US$)  2021
..                            ...   ...
103  GDP per capita (current US$)  1994
104  GDP per capita (current US$)  1993
105  GDP per capita (current US$)  1992
106  GDP per capita (current US$)  1991
107  GDP per capita (current US$)  1990

[108 rows x 2 columns]

## 2.5 Select Rows and Columns

Combine row filtering with column selection.

In [32]:
gdp_data.query("country in ['Canada', 'Australia']")[['country', 'date', 'indicator', 'value']]

      country  date                     indicator         value
0   Australia  2025  GDP per capita (current US$)           NaN
1   Australia  2024  GDP per capita (current US$)  64603.985631
2   Australia  2023  GDP per capita (current US$)  65058.377315
3   Australia  2022  GDP per capita (current US$)  65169.519112
4   Australia  2021  GDP per capita (current US$)  60758.904440
..        ...   ...                           ...           ...
67     Canada  1994  GDP per capita (current US$)  19997.623737
68     Canada  1993  GDP per capita (current US$)  20186.798878
69     Canada  1992  GDP per capita (current US$)  20950.330529
70     Canada  1991  GDP per capita (current US$)  21846.793047
71     Canada  1990  GDP per capita (current US$)  21525.861139

[72 rows x 4 columns]

## 2.6 Rename Columns

Rename columns in the dataframe.

In [35]:
gdp_data.head(1)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),Australia,AUS,2025,NaN,NaN,NaN,1

In [36]:
rename_dictionary = {"value" : "GDP","countryiso3code":"sheenascountries"}
gdp_data.rename(rename_dictionary, axis=1).head(2)

,indicator,country,sheenascountries,date,GDP,unit,obs_status,decimal
0,GDP per capita (current US$),Australia,AUS,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),Australia,AUS,2024,64603.985631,NaN,NaN,1

In [64]:
gdp_data.indicator.replace(
    {'GDP per capita (current US$)' : "GDP"})

0      GDP
1      GDP
2      GDP
3      GDP
4      GDP
      ...
103    GDP
104    GDP
105    GDP
106    GDP
107    GDP
Name: indicator, Length: 108, dtype: object